// generated by newgenasym  Thu Oct 09 19:38:36 2014


module ddr3_2gb_x16_sdram (a, ba, \cas* , ck, \ck* , cke, \cs* , dq, ldm, ldqs, \ldqs* , odt, \ras* ,
        \reset* , udm, udqs, \udqs* , \we* , zq);
    input [13:0] a;
    input [2:0] ba;
    input \cas* ;
    input ck;
    input \ck* ;
    input cke;
    input \cs* ;
    inout [15:0] dq;
    input ldm;
    inout ldqs;
    inout \ldqs* ;
    input odt;
    input \ras* ;
    input \reset* ;
    input udm;
    inout udqs;
    inout \udqs* ;
    input \we* ;
    inout zq;


    initial
        begin
        end

endmodule
