-- generated by newgenasym Thu Oct 09 19:38:36 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ddr3_2gb_x16_sdram is
    port (    
	A:         IN     STD_LOGIC_VECTOR (13 DOWNTO 0);    
	BA:        IN     STD_LOGIC_VECTOR (2 DOWNTO 0);    
	\cas*\:    IN     STD_LOGIC;    
	CK:        IN     STD_LOGIC;    
	\ck*\:     IN     STD_LOGIC;    
	CKE:       IN     STD_LOGIC;    
	\cs*\:     IN     STD_LOGIC;    
	DQ:        INOUT  STD_LOGIC_VECTOR (15 DOWNTO 0);    
	LDM:       IN     STD_LOGIC;    
	LDQS:      INOUT  STD_LOGIC;    
	\ldqs*\:   INOUT  STD_LOGIC;    
	ODT:       IN     STD_LOGIC;    
	\ras*\:    IN     STD_LOGIC;    
	\reset*\:  IN     STD_LOGIC;    
	UDM:       IN     STD_LOGIC;    
	UDQS:      INOUT  STD_LOGIC;    
	\udqs*\:   INOUT  STD_LOGIC;    
	\we*\:     IN     STD_LOGIC;    
	ZQ:        INOUT  STD_LOGIC);
end ddr3_2gb_x16_sdram;
