// generated by newgenasym  Thu Oct 09 19:31:01 2014


module dvi (\5v , \5v_gndrtn , a_blue, a_gnd_rtn, a_grn, a_hsync, a_red,
        a_vsync, ddc_clk, ddc_data, shld_0_5, shld_1_3, shld_2_4,
        tdms_clk_shld, tdms_clkn, tdms_clkp, tdms_data_dn,
        tdms_data_dp);
    inout \5v ;
    inout \5v_gndrtn ;
    inout a_blue;
    inout a_gnd_rtn;
    inout a_grn;
    inout a_hsync;
    inout a_red;
    inout a_vsync;
    inout ddc_clk;
    inout ddc_data;
    inout shld_0_5;
    inout shld_1_3;
    inout shld_2_4;
    inout tdms_clk_shld;
    inout tdms_clkn;
    inout tdms_clkp;
    inout [5:0] tdms_data_dn;
    inout [5:0] tdms_data_dp;


    initial
        begin
        end

endmodule
