-- generated by newgenasym Fri May 25 14:24:25 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AGILENTHBT_NPN is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC;    
	P3:        INOUT  STD_LOGIC);
end AGILENTHBT_NPN;
