-- generated by newgenasym Fri Jan 05 13:38:57 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ADSDIODE is
    port (    
	A1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC);
end ADSDIODE;
