// generated by newgenasym  Fri Jan 05 13:49:11 2007


module y6p_eqn (p1, p10, p11, p12, p2, p3, p4, p5, p6, p7, p8, p9);
    inout p1;
    inout p10;
    inout p11;
    inout p12;
    inout p2;
    inout p3;
    inout p4;
    inout p5;
    inout p6;
    inout p7;
    inout p8;
    inout p9;


    initial
        begin
        end

endmodule
