// generated by newgenasym  Mon Sep 09 18:52:21 2013


module tpd4eusb30 (\d1* , d1_p, \d2* , d2_p, gnd, gnd1);
    input \d1* ;
    input d1_p;
    input \d2* ;
    input d2_p;
    input gnd;
    input gnd1;


    initial
        begin
        end

endmodule
