-- generated by newgenasym Mon Sep 09 18:52:21 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tpd4eusb30 is
    port (    
	\d1*\:     IN     STD_LOGIC;    
	D1_P:      IN     STD_LOGIC;    
	\d2*\:     IN     STD_LOGIC;    
	D2_P:      IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC);
end tpd4eusb30;
