// generated by newgenasym  Thu Oct 09 19:37:13 2014


module vga (b_gnd, blue_vid, g_gnd, gnd, green_vid, hsync, id0, id1, id2,
        id3, keypin, r_gnd, red_vid, s_gnd, vsync);
    inout b_gnd;
    inout blue_vid;
    inout g_gnd;
    inout gnd;
    inout green_vid;
    inout hsync;
    inout id0;
    inout id1;
    inout id2;
    inout id3;
    inout keypin;
    inout r_gnd;
    inout red_vid;
    inout s_gnd;
    inout vsync;


    initial
        begin
        end

endmodule
