-- generated by newgenasym Thu Oct 09 19:37:13 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity vga is
    port (    
	B_GND:     INOUT  STD_LOGIC;    
	BLUE_VID:  INOUT  STD_LOGIC;    
	G_GND:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	GREEN_VID: INOUT  STD_LOGIC;    
	HSYNC:     INOUT  STD_LOGIC;    
	ID0:       INOUT  STD_LOGIC;    
	ID1:       INOUT  STD_LOGIC;    
	ID2:       INOUT  STD_LOGIC;    
	ID3:       INOUT  STD_LOGIC;    
	KEYPIN:    INOUT  STD_LOGIC;    
	R_GND:     INOUT  STD_LOGIC;    
	RED_VID:   INOUT  STD_LOGIC;    
	S_GND:     INOUT  STD_LOGIC;    
	VSYNC:     INOUT  STD_LOGIC);
end vga;
