-- generated by newgenasym Fri Jan 05 13:39:41 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ADS_FET is
    port (    
	DRAIN:     INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC;    
	SOURCE:    INOUT  STD_LOGIC);
end ADS_FET;
