// generated by newgenasym  Fri Feb 16 18:46:46 2018


module custom_pcie8 (gnd_a12, gnd_a15, gnd_a18, gnd_a20, gnd_a23, gnd_a24,
        gnd_a27, gnd_a28, gnd_a31, gnd_a34, gnd_a37, gnd_a38,
        gnd_a4, gnd_a41, gnd_a42, gnd_a45, gnd_a46, gnd_a49,
        gnd_b13, gnd_b16, gnd_b18, gnd_b21, gnd_b22, gnd_b25,
        gnd_b26, gnd_b29, gnd_b32, gnd_b35, gnd_b36, gnd_b39,
        gnd_b4, gnd_b40, gnd_b43, gnd_b44, gnd_b47, gnd_b49, gnd_b7,
        hsin0, hsin1, hsin2, hsin3, hsin4, hsin5, hsin6, hsin7, hsip0,
        hsip1, hsip2, hsip3, hsip4, hsip5, hsip6, hsip7, hson0, hson1,
        hson2, hson3, hson4, hson5, hson6, hson7, hsop0, hsop1, hsop2,
        hsop3, hsop4, hsop5, hsop6, hsop7, perst, prsnt1, prsnt2,
        prsnt2x1, prsnt2x4, refclkn, refclkp, smclk, smdat, tck, tdi,
        tdo, tms, trst, v12_a2, v12_a3, v12_b1, v12_b2, v3_3_a10,
        v3_3_a9, v3_3_b8, vux3_3, wake);
    inout gnd_a12;
    inout gnd_a15;
    inout gnd_a18;
    inout gnd_a20;
    inout gnd_a23;
    inout gnd_a24;
    inout gnd_a27;
    inout gnd_a28;
    inout gnd_a31;
    inout gnd_a34;
    inout gnd_a37;
    inout gnd_a38;
    inout gnd_a4;
    inout gnd_a41;
    inout gnd_a42;
    inout gnd_a45;
    inout gnd_a46;
    inout gnd_a49;
    inout gnd_b13;
    inout gnd_b16;
    inout gnd_b18;
    inout gnd_b21;
    inout gnd_b22;
    inout gnd_b25;
    inout gnd_b26;
    inout gnd_b29;
    inout gnd_b32;
    inout gnd_b35;
    inout gnd_b36;
    inout gnd_b39;
    inout gnd_b4;
    inout gnd_b40;
    inout gnd_b43;
    inout gnd_b44;
    inout gnd_b47;
    inout gnd_b49;
    inout gnd_b7;
    inout hsin0;
    inout hsin1;
    inout hsin2;
    inout hsin3;
    inout hsin4;
    inout hsin5;
    inout hsin6;
    inout hsin7;
    inout hsip0;
    inout hsip1;
    inout hsip2;
    inout hsip3;
    inout hsip4;
    inout hsip5;
    inout hsip6;
    inout hsip7;
    inout hson0;
    inout hson1;
    inout hson2;
    inout hson3;
    inout hson4;
    inout hson5;
    inout hson6;
    inout hson7;
    inout hsop0;
    inout hsop1;
    inout hsop2;
    inout hsop3;
    inout hsop4;
    inout hsop5;
    inout hsop6;
    inout hsop7;
    inout perst;
    inout prsnt1;
    inout prsnt2;
    inout prsnt2x1;
    inout prsnt2x4;
    inout refclkn;
    inout refclkp;
    inout smclk;
    inout smdat;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;
    inout trst;
    inout v12_a2;
    inout v12_a3;
    inout v12_b1;
    inout v12_b2;
    inout v3_3_a10;
    inout v3_3_a9;
    inout v3_3_b8;
    inout vux3_3;
    inout wake;


    initial
        begin
        end

endmodule
