-- generated by newgenasym Fri Jan 05 13:43:16 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LPF_POLEZERO is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC);
end LPF_POLEZERO;
