-- generated by newgenasym Fri Jan 05 13:43:21 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AGC_AMP is
    port (    
	rf_in:     INOUT  STD_LOGIC;    
	rf_out:    INOUT  STD_LOGIC;    
	vc:        INOUT  STD_LOGIC);
end AGC_AMP;
