// generated by newgenasym  Thu Oct 09 19:32:07 2014


module sata (dp_an, dp_ap, dp_bn, dp_bp, g1, g2, g3);
    inout dp_an;
    inout dp_ap;
    inout dp_bn;
    inout dp_bp;
    inout g1;
    inout g2;
    inout g3;


    initial
        begin
        end

endmodule
