-- generated by newgenasym Thu Oct 09 19:32:07 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sata is
    port (    
	DP_AN:     INOUT  STD_LOGIC;    
	DP_AP:     INOUT  STD_LOGIC;    
	DP_BN:     INOUT  STD_LOGIC;    
	DP_BP:     INOUT  STD_LOGIC;    
	G1:        INOUT  STD_LOGIC;    
	G2:        INOUT  STD_LOGIC;    
	G3:        INOUT  STD_LOGIC);
end sata;
