// generated by newgenasym  Fri Oct 17 06:38:04 2014


module viper_asic (bclk_dn, bclk_dp, bclk_itp_dn, bclk_itp_dp, bpm_m,
        \cat_err* , comp0, \dbr* , ddr0_ba, \ddr0_cas* , ddr0_cke,
        ddr0_clk_m, ddr0_clk_p, ddr0_cs_m, ddr0_dq, ddr0_dqs_m,
        ddr0_dqs_p, ddr0_ma, ddr0_odt, \ddr0_ras* , \ddr0_reset* ,
        \ddr0_we* , ddr1_ba, \ddr1_cas* , ddr1_cke, ddr1_clk_m,
        ddr1_clk_p, ddr1_cs_m, ddr1_dq, ddr1_dqs_m, ddr1_dqs_p,
        ddr1_ma, ddr1_odt, \ddr1_ras* , \ddr1_reset* , \ddr1_we* ,
        ddr_comp, ddr_vref, dvi_a_gnd_rtn, dvi_a_horz_sync,
        dvi_analog_blue, dvi_analog_grn, dvi_analog_red,
        dvi_ddc_clk, dvi_ddc_data, dvi_tdms_clk_shld,
        dvi_tdms_clkn, dvi_tdms_clkp, dvi_tdms_dn, dvi_tdms_dp,
        dvi_tdms_shld05, dvi_tdms_shld13, dvi_tdms_shld24,
        dvi_vsync, fc_ah5, fpga_ppc_ale_a, fpga_ppc_ale_b,
        fpga_ppc_as, fpga_ppc_baddr28, fpga_ppc_baddr29,
        fpga_ppc_baddr30, fpga_ppc_bb, fpga_ppc_bg, fpga_ppc_bi,
        fpga_ppc_br, fpga_ppc_bs_a0, fpga_ppc_bs_a1,
        fpga_ppc_bs_a2, fpga_ppc_bs_a3, fpga_ppc_burst,
        fpga_ppc_clkout, fpga_ppc_cr_irq3, fpga_ppc_cs2,
        fpga_ppc_data, fpga_ppc_rd_wr, gpio0, gpio1, gpio10,
        gpio11, gpio12, gpio13, gpio14, gpio15, gpio16, gpio17,
        gpio18, gpio19, gpio2, gpio20, gpio21, gpio22, gpio23,
        gpio24, gpio25, gpio26, gpio27, gpio28, gpio29, gpio3,
        gpio30, gpio31, gpio32, gpio33, gpio34, gpio35, gpio36,
        gpio37, gpio38, gpio39, gpio4, gpio40, gpio5, gpio6, gpio7,
        gpio8, gpio9, hdmi_cec, hdmi_ddc_clk, hdmi_ddc_data,
        hdmi_hpdtct, hdmi_tdms_clkn, hdmi_tdms_clkp,
        hdmi_tdms_clkshld, hdmi_tdms_dn, hdmi_tdms_dp,
        hdmi_tdms_shld0, hdmi_tdms_shld1, hdmi_tdms_shld2,
        isense, pcie_rxn, pcie_rxp, pcie_txn, pcie_txp, peci,
        ppc_bdip_gpl_b5, \prdy* , \preq* , \prochot* , \psi* , \reset* ,
        sata3_compi, sata3_compo, sata_bias, sata_clk, sata_compi,
        sata_compo, \sata_led* , sata_rxn, sata_rxp, sata_txn,
        sata_txp, sdataout0, sdataout1, \sktocc* , sload, tck, tdi,
        tdo, \thermtrip* , tms, \trst* , usb3_rxn, usb3_rxp, usb3_txn,
        usb3_txp, vcc_sense, vccpwrgood, vddpwrgood, vga_bgnd,
        vga_bvid, vga_ggnd, vga_gvid, vga_hsync, vga_id0, vga_id1,
        vga_id2, vga_id3, vga_rgnd, vga_rvid, vga_sgnd, vga_vsync,
        vid, vss_sense, vss_sense_vtt, vtt_sense, vtt_vid2,
        vtt_vid3, vtt_vid4, vttpwrgood);
    input bclk_dn;
    input bclk_dp;
    output bclk_itp_dn;
    output bclk_itp_dp;
    inout [7:0] bpm_m;
    inout \cat_err* ;
    input comp0;
    input \dbr* ;
    output [2:0] ddr0_ba;
    output \ddr0_cas* ;
    output [3:0] ddr0_cke;
    output [3:0] ddr0_clk_m;
    output [3:0] ddr0_clk_p;
    output [3:0] ddr0_cs_m;
    inout [63:0] ddr0_dq;
    inout [7:0] ddr0_dqs_m;
    inout [7:0] ddr0_dqs_p;
    output [15:0] ddr0_ma;
    output [3:0] ddr0_odt;
    output \ddr0_ras* ;
    output \ddr0_reset* ;
    output \ddr0_we* ;
    output [2:0] ddr1_ba;
    output \ddr1_cas* ;
    output [3:0] ddr1_cke;
    output [3:0] ddr1_clk_m;
    output [3:0] ddr1_clk_p;
    output [3:0] ddr1_cs_m;
    inout [63:0] ddr1_dq;
    inout [7:0] ddr1_dqs_m;
    inout [7:0] ddr1_dqs_p;
    output [15:0] ddr1_ma;
    output [3:0] ddr1_odt;
    output \ddr1_ras* ;
    output \ddr1_reset* ;
    output \ddr1_we* ;
    input [2:0] ddr_comp;
    input ddr_vref;
    output dvi_a_gnd_rtn;
    output dvi_a_horz_sync;
    output dvi_analog_blue;
    output dvi_analog_grn;
    output dvi_analog_red;
    output dvi_ddc_clk;
    output dvi_ddc_data;
    output dvi_tdms_clk_shld;
    output dvi_tdms_clkn;
    output dvi_tdms_clkp;
    output [5:0] dvi_tdms_dn;
    output [5:0] dvi_tdms_dp;
    output dvi_tdms_shld05;
    output dvi_tdms_shld13;
    output dvi_tdms_shld24;
    output dvi_vsync;
    inout fc_ah5;
    input fpga_ppc_ale_a;
    input fpga_ppc_ale_b;
    input fpga_ppc_as;
    input fpga_ppc_baddr28;
    input fpga_ppc_baddr29;
    input fpga_ppc_baddr30;
    input fpga_ppc_bb;
    input fpga_ppc_bg;
    input fpga_ppc_bi;
    input fpga_ppc_br;
    input fpga_ppc_bs_a0;
    input fpga_ppc_bs_a1;
    input fpga_ppc_bs_a2;
    input fpga_ppc_bs_a3;
    input fpga_ppc_burst;
    input fpga_ppc_clkout;
    input fpga_ppc_cr_irq3;
    input fpga_ppc_cs2;
    inout [31:0] fpga_ppc_data;
    input fpga_ppc_rd_wr;
    inout gpio0;
    inout gpio1;
    inout gpio10;
    inout gpio11;
    inout gpio12;
    inout gpio13;
    inout gpio14;
    inout gpio15;
    inout gpio16;
    inout gpio17;
    inout gpio18;
    inout gpio19;
    inout gpio2;
    inout gpio20;
    inout gpio21;
    inout gpio22;
    inout gpio23;
    inout gpio24;
    inout gpio25;
    inout gpio26;
    inout gpio27;
    inout gpio28;
    inout gpio29;
    inout gpio3;
    inout gpio30;
    inout gpio31;
    inout gpio32;
    inout gpio33;
    inout gpio34;
    inout gpio35;
    inout gpio36;
    inout gpio37;
    inout gpio38;
    inout gpio39;
    inout gpio4;
    inout gpio40;
    inout gpio5;
    inout gpio6;
    inout gpio7;
    inout gpio8;
    inout gpio9;
    input hdmi_cec;
    input hdmi_ddc_clk;
    input hdmi_ddc_data;
    input hdmi_hpdtct;
    input hdmi_tdms_clkn;
    input hdmi_tdms_clkp;
    input hdmi_tdms_clkshld;
    input [2:0] hdmi_tdms_dn;
    input [2:0] hdmi_tdms_dp;
    input hdmi_tdms_shld0;
    input hdmi_tdms_shld1;
    input hdmi_tdms_shld2;
    input isense;
    input [7:0] pcie_rxn;
    input [7:0] pcie_rxp;
    output [7:0] pcie_txn;
    output [7:0] pcie_txp;
    inout peci;
    input ppc_bdip_gpl_b5;
    output \prdy* ;
    input \preq* ;
    inout \prochot* ;
    output \psi* ;
    input \reset* ;
    inout sata3_compi;
    inout sata3_compo;
    inout sata_bias;
    inout sata_clk;
    inout sata_compi;
    inout sata_compo;
    inout \sata_led* ;
    input [5:0] sata_rxn;
    input [5:0] sata_rxp;
    output [5:0] sata_txn;
    output [5:0] sata_txp;
    inout sdataout0;
    inout sdataout1;
    output \sktocc* ;
    inout sload;
    input tck;
    input tdi;
    output tdo;
    output \thermtrip* ;
    input tms;
    input \trst* ;
    input [3:0] usb3_rxn;
    input [3:0] usb3_rxp;
    output [3:0] usb3_txn;
    output [3:0] usb3_txp;
    output vcc_sense;
    input vccpwrgood;
    input vddpwrgood;
    output vga_bgnd;
    output vga_bvid;
    output vga_ggnd;
    output vga_gvid;
    output vga_hsync;
    output vga_id0;
    output vga_id1;
    output vga_id2;
    output vga_id3;
    output vga_rgnd;
    output vga_rvid;
    output vga_sgnd;
    output vga_vsync;
    inout [7:0] vid;
    output vss_sense;
    output vss_sense_vtt;
    output vtt_sense;
    output vtt_vid2;
    output vtt_vid3;
    output vtt_vid4;
    input vttpwrgood;


    initial
        begin
        end

endmodule
