// generated by newgenasym  Fri Jan 05 13:49:16 2007


module z4p_eqn (p1, p2, p3, p4, p5, p6, p7, p8);
    inout p1;
    inout p2;
    inout p3;
    inout p4;
    inout p5;
    inout p6;
    inout p7;
    inout p8;


    initial
        begin
        end

endmodule
