-- generated by newgenasym Fri Jan 05 13:49:16 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity Z4P_EQN is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC;    
	P3:        INOUT  STD_LOGIC;    
	P4:        INOUT  STD_LOGIC;    
	P5:        INOUT  STD_LOGIC;    
	P6:        INOUT  STD_LOGIC;    
	P7:        INOUT  STD_LOGIC;    
	P8:        INOUT  STD_LOGIC);
end Z4P_EQN;
