-- generated by newgenasym Fri Oct 17 06:50:23 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity res is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end res;
