// generated by newgenasym  Mon Sep 09 17:07:47 2013


module usb_30 (d_am, d_ap, gnd, gnd_drn, shld1, shld2, stda_ssrx_m,
        stda_ssrx_p, stda_sstx_m, stda_sstx_p, vbus);
    inout d_am;
    inout d_ap;
    inout gnd;
    inout gnd_drn;
    inout shld1;
    inout shld2;
    inout stda_ssrx_m;
    inout stda_ssrx_p;
    inout stda_sstx_m;
    inout stda_sstx_p;
    inout vbus;


    initial
        begin
        end

endmodule
