-- generated by newgenasym Mon Sep 09 17:07:47 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity usb_30 is
    port (    
	D_AM:      INOUT  STD_LOGIC;    
	D_AP:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	GND_DRN:   INOUT  STD_LOGIC;    
	SHLD1:     INOUT  STD_LOGIC;    
	SHLD2:     INOUT  STD_LOGIC;    
	STDA_SSRX_M: INOUT  STD_LOGIC;    
	STDA_SSRX_P: INOUT  STD_LOGIC;    
	STDA_SSTX_M: INOUT  STD_LOGIC;    
	STDA_SSTX_P: INOUT  STD_LOGIC;    
	VBUS:      INOUT  STD_LOGIC);
end usb_30;
