// generated by newgenasym  Fri Oct 17 06:51:00 2014


module lmz14203 (en, ep, fb, gnd, ron, ss, vin, vout);
    input en;
    input ep;
    input fb;
    input gnd;
    inout ron;
    inout ss;
    input vin;
    output vout;


    initial
        begin
        end

endmodule
