-- generated by newgenasym Fri Oct 17 06:51:00 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lmz14203 is
    port (    
	EN:        IN     STD_LOGIC;    
	EP:        IN     STD_LOGIC;    
	FB:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	RON:       INOUT  STD_LOGIC;    
	SS:        INOUT  STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VOUT:      OUT    STD_LOGIC);
end lmz14203;
