-- generated by newgenasym Thu Oct 09 20:05:57 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cap is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end cap;
